### ISSUE TITLE
Drawer handler closes opened drawerLayout when releasing finger from handler hit rect

### ISSUE THREAD

**Issue by Allier** [codetwisted/android-widget#7]
Steps to reproduce:
Open drawer by dragging a handler and release finger while it's still in handler hit area

**Comment by vrishe** [comment]
This problem comes from the way, handle click is being processed. We need to track down whether, drawer handle not moved in order to perform it's click action or not.

I tend to re-design the whole internal state-machine, so to keep states clear and consistent.

**Comment by vrishe** [comment]
@Allier, this issue seem to be fixed for me. Please check it out!

**Comment by Allier** [comment]
@vrishe, can't reproduce it either, merge and close
